/* Generated by re2c 4.1 on Thu Feb 20 17:19:16 2025 */
#line 1 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
#include "lexer.hpp"
#include "location.hpp"
#include "parser.hpp"

#include <cassert>
#include <cctype>
#include <string_view>

fermi::lexer::lexer(std::string_view source)
    : source_(source), curr_(source.cbegin()) {}

void fermi::lexer::reset() {
  loc_ = parser::location_type{};
  curr_ = source_.cbegin();
}

fermi::parser::symbol_type fermi::lexer::next_token() {
  skip_to_token();
  loc_.step();
  std::string_view::const_iterator first = curr_;
  std::string_view::const_iterator marker = curr_;
  if (curr_ == source_.cend()) {
    loc_.columns(curr_ - first);
    return parser::make_YYEOF(loc_);
  }
  
#line 30 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
{
	char yych;
	unsigned int yyaccept = 0;
	yych = *curr_;
	switch (yych) {
		case '!': goto yy3;
		case '"': goto yy5;
		case '%': goto yy6;
		case '&': goto yy8;
		case '\'': goto yy9;
		case '(': goto yy10;
		case ')': goto yy11;
		case '*': goto yy12;
		case '+': goto yy14;
		case ',': goto yy16;
		case '-': goto yy17;
		case '.': goto yy19;
		case '/': goto yy21;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy23;
		case ':': goto yy25;
		case ';': goto yy26;
		case '<': goto yy27;
		case '=': goto yy29;
		case '>': goto yy31;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy33;
		case '[': goto yy36;
		case ']': goto yy37;
		case '^': goto yy38;
		case 'a': goto yy40;
		case 'b': goto yy41;
		case 'c': goto yy42;
		case 'd': goto yy43;
		case 'e': goto yy44;
		case 'f': goto yy45;
		case 'i': goto yy46;
		case 'l': goto yy47;
		case 'm': goto yy48;
		case 'n': goto yy49;
		case 'o': goto yy50;
		case 't': goto yy51;
		case '{': goto yy52;
		case '|': goto yy53;
		case '}': goto yy54;
		default: goto yy1;
	}
yy1:
	++curr_;
yy2:
#line 289 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_YYerror(loc_);
    }
#line 133 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy3:
	yych = *++curr_;
	switch (yych) {
		case '=': goto yy55;
		default: goto yy4;
	}
yy4:
#line 280 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_BANG(loc_);
    }
#line 146 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy5:
	yych = *++curr_;
	switch (yych) {
		case '"': goto yy56;
		default: goto yy5;
	}
yy6:
	yych = *++curr_;
	switch (yych) {
		case '=': goto yy57;
		default: goto yy7;
	}
yy7:
#line 268 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_PERCENT(loc_);
    }
#line 165 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy8:
	++curr_;
#line 140 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_AMPERSAND(loc_);
    }
#line 173 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy9:
	yyaccept = 0;
	yych = *(marker = ++curr_);
	switch (yych) {
		case '\'': goto yy2;
		default: goto yy58;
	}
yy10:
	++curr_;
#line 160 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_LEFT_PARENTHESIS(loc_);
    }
#line 188 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy11:
	++curr_;
#line 156 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_RIGHT_PARENTHESIS(loc_);
    }
#line 196 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy12:
	yych = *++curr_;
	switch (yych) {
		case '=': goto yy60;
		default: goto yy13;
	}
yy13:
#line 144 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_STAR(loc_);
    }
#line 209 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy14:
	yych = *++curr_;
	switch (yych) {
		case '=': goto yy61;
		default: goto yy15;
	}
yy15:
#line 252 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_PLUS(loc_);
    }
#line 222 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy16:
	++curr_;
#line 168 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_COMMA(loc_);
    }
#line 230 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy17:
	yych = *++curr_;
	switch (yych) {
		case '=': goto yy62;
		case '>': goto yy63;
		default: goto yy18;
	}
yy18:
#line 256 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_MINUS(loc_);
    }
#line 244 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy19:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy64;
		default: goto yy20;
	}
yy20:
#line 276 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_DOT(loc_);
    }
#line 266 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy21:
	yych = *++curr_;
	switch (yych) {
		case '/': goto yy66;
		case '=': goto yy68;
		default: goto yy22;
	}
yy22:
#line 260 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_SLASH(loc_);
    }
#line 280 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy23:
	yyaccept = 1;
	yych = *(marker = ++curr_);
	switch (yych) {
		case '.': goto yy69;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy23;
		case 'E':
		case 'e': goto yy70;
		default: goto yy24;
	}
yy24:
#line 32 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_INTEGER(std::string_view{first, curr_}, loc_);
    }
#line 306 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy25:
	++curr_;
#line 172 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_COLON(loc_);
    }
#line 314 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy26:
	++curr_;
#line 180 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_SEMICOLON(loc_);
    }
#line 322 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy27:
	yych = *++curr_;
	switch (yych) {
		case '-': goto yy71;
		case '=': goto yy72;
		default: goto yy28;
	}
yy28:
#line 232 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_LESS(loc_);
    }
#line 336 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy29:
	yych = *++curr_;
	switch (yych) {
		case '=': goto yy74;
		default: goto yy30;
	}
yy30:
#line 164 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_ASSIGN(loc_);
    }
#line 349 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy31:
	yych = *++curr_;
	switch (yych) {
		case '=': goto yy75;
		default: goto yy32;
	}
yy32:
#line 240 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_GREATER(loc_);
    }
#line 362 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy33:
	yych = *++curr_;
yy34:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy33;
		default: goto yy35;
	}
yy35:
#line 130 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      if (!lex_as_typename_) {
        return parser::make_IDENTIFIER(std::string_view{first, curr_}, loc_);
      } else {
        lex_as_typename_ = false;
        return parser::make_TYPE_NAME(std::string_view{first, curr_}, loc_);
      }
    }
#line 442 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy36:
	++curr_;
#line 148 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_LEFT_BRACKET(loc_);
     }
#line 450 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy37:
	++curr_;
#line 152 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_RIGHT_BRACKET(loc_);
    }
#line 458 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy38:
	yych = *++curr_;
	switch (yych) {
		case '=': goto yy76;
		default: goto yy39;
	}
yy39:
#line 272 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_CARET(loc_);
    }
#line 471 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy40:
	yych = *++curr_;
	switch (yych) {
		case 'n': goto yy77;
		case 's': goto yy78;
		default: goto yy34;
	}
yy41:
	yych = *++curr_;
	switch (yych) {
		case 'o': goto yy80;
		default: goto yy34;
	}
yy42:
	yych = *++curr_;
	switch (yych) {
		case 'o': goto yy81;
		default: goto yy34;
	}
yy43:
	yych = *++curr_;
	switch (yych) {
		case 'e': goto yy82;
		default: goto yy34;
	}
yy44:
	yych = *++curr_;
	switch (yych) {
		case 'l': goto yy83;
		case 'x': goto yy84;
		default: goto yy34;
	}
yy45:
	yych = *++curr_;
	switch (yych) {
		case 'a': goto yy85;
		default: goto yy34;
	}
yy46:
	yych = *++curr_;
	switch (yych) {
		case 'n': goto yy86;
		default: goto yy34;
	}
yy47:
	yych = *++curr_;
	switch (yych) {
		case 'e': goto yy88;
		default: goto yy34;
	}
yy48:
	yych = *++curr_;
	switch (yych) {
		case 'o': goto yy89;
		case 'u': goto yy90;
		default: goto yy34;
	}
yy49:
	yych = *++curr_;
	switch (yych) {
		case 'o': goto yy91;
		default: goto yy34;
	}
yy50:
	yych = *++curr_;
	switch (yych) {
		case 'r': goto yy92;
		case 'u': goto yy94;
		default: goto yy34;
	}
yy51:
	yych = *++curr_;
	switch (yych) {
		case 'h': goto yy95;
		case 'r': goto yy96;
		default: goto yy34;
	}
yy52:
	++curr_;
#line 216 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_LEFT_BRACE(loc_);
    }
#line 556 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy53:
	++curr_;
#line 284 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_PIPE(loc_);
    }
#line 564 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy54:
	++curr_;
#line 220 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_RIGHT_BRACE(loc_);
    }
#line 572 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy55:
	++curr_;
#line 228 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_BANG_EQUAL(loc_);
    }
#line 580 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy56:
	++curr_;
#line 47 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_STRING(std::string_view{first, curr_}, loc_);
    }
#line 588 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy57:
	++curr_;
#line 208 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_PERCENT_EQUAL(loc_);
    }
#line 596 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy58:
	yych = *++curr_;
	switch (yych) {
		case '\'': goto yy97;
		default: goto yy59;
	}
yy59:
	curr_ = marker;
	switch (yyaccept) {
		case 0: goto yy2;
		case 1: goto yy24;
		default: goto yy65;
	}
yy60:
	++curr_;
#line 196 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_STAR_EQUAL(loc_);
    }
#line 617 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy61:
	++curr_;
#line 188 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_PLUS_EQUAL(loc_);
    }
#line 625 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy62:
	++curr_;
#line 192 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_MINUS_EQUAL(loc_);
    }
#line 633 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy63:
	++curr_;
#line 176 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_RIGHT_ARROW(loc_);
    }
#line 641 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy64:
	yyaccept = 2;
	yych = *(marker = ++curr_);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy64;
		case 'E':
		case 'e': goto yy98;
		default: goto yy65;
	}
yy65:
#line 42 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_FLOAT(std::string_view{first, curr_}, loc_);
    }
#line 666 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy66:
	yych = *++curr_;
	switch (yych) {
		case '=': goto yy99;
		default: goto yy67;
	}
yy67:
#line 264 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_SLASH_SLASH(loc_);
    }
#line 679 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy68:
	++curr_;
#line 200 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_SLASH_EQUAL(loc_);
    }
#line 687 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy69:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy64;
		default: goto yy59;
	}
yy70:
	yych = *++curr_;
	switch (yych) {
		case '+': goto yy100;
		case '-': goto yy101;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy102;
		default: goto yy59;
	}
yy71:
	++curr_;
#line 184 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_LEFT_ARROW(loc_);
    }
#line 727 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy72:
	yych = *++curr_;
	switch (yych) {
		case '>': goto yy103;
		default: goto yy73;
	}
yy73:
#line 236 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_LESS_EQUAL(loc_);
    }
#line 740 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy74:
	++curr_;
#line 224 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_EQUAL_EQUAL(loc_);
    }
#line 748 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy75:
	++curr_;
#line 244 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_GREATER_EQUAL(loc_);
    }
#line 756 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy76:
	++curr_;
#line 212 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_CARET_EQUAL(loc_);
    }
#line 764 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy77:
	yych = *++curr_;
	switch (yych) {
		case 'd': goto yy104;
		default: goto yy34;
	}
yy78:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy33;
		default: goto yy79;
	}
yy79:
#line 61 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_AS(loc_);
    }
#line 844 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy80:
	yych = *++curr_;
	switch (yych) {
		case 'o': goto yy106;
		default: goto yy34;
	}
yy81:
	yych = *++curr_;
	switch (yych) {
		case 'm': goto yy107;
		default: goto yy34;
	}
yy82:
	yych = *++curr_;
	switch (yych) {
		case 'f': goto yy108;
		default: goto yy34;
	}
yy83:
	yych = *++curr_;
	switch (yych) {
		case 's': goto yy109;
		default: goto yy34;
	}
yy84:
	yych = *++curr_;
	switch (yych) {
		case 'p': goto yy110;
		default: goto yy34;
	}
yy85:
	yych = *++curr_;
	switch (yych) {
		case 'l': goto yy111;
		default: goto yy34;
	}
yy86:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy33;
		default: goto yy87;
	}
yy87:
#line 93 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_IN(loc_);
    }
#line 954 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy88:
	yych = *++curr_;
	switch (yych) {
		case 't': goto yy112;
		default: goto yy34;
	}
yy89:
	yych = *++curr_;
	switch (yych) {
		case 'v': goto yy114;
		default: goto yy34;
	}
yy90:
	yych = *++curr_;
	switch (yych) {
		case 't': goto yy115;
		default: goto yy34;
	}
yy91:
	yych = *++curr_;
	switch (yych) {
		case 't': goto yy116;
		default: goto yy34;
	}
yy92:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy33;
		default: goto yy93;
	}
yy93:
#line 117 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_OR(loc_);
    }
#line 1052 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy94:
	yych = *++curr_;
	switch (yych) {
		case 't': goto yy118;
		default: goto yy34;
	}
yy95:
	yych = *++curr_;
	switch (yych) {
		case 'i': goto yy120;
		default: goto yy34;
	}
yy96:
	yych = *++curr_;
	switch (yych) {
		case 'u': goto yy121;
		default: goto yy34;
	}
yy97:
	++curr_;
#line 52 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_CHARACTER(std::string_view{first, curr_}, loc_);
    }
#line 1078 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy98:
	yych = *++curr_;
	switch (yych) {
		case '+':
		case '-': goto yy122;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy123;
		default: goto yy59;
	}
yy99:
	++curr_;
#line 204 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_SLASH_SLASH_EQUAL(loc_);
    }
#line 1103 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy100:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy102;
		default: goto yy59;
	}
yy101:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy124;
		default: goto yy59;
	}
yy102:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy102;
		default: goto yy24;
	}
yy103:
	++curr_;
#line 248 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_SPACESHIP(loc_);
    }
#line 1156 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy104:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy33;
		default: goto yy105;
	}
yy105:
#line 57 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_AND(loc_);
    }
#line 1230 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy106:
	yych = *++curr_;
	switch (yych) {
		case 'l': goto yy126;
		default: goto yy34;
	}
yy107:
	yych = *++curr_;
	switch (yych) {
		case 'p': goto yy128;
		default: goto yy34;
	}
yy108:
	yych = *++curr_;
	switch (yych) {
		case 'i': goto yy129;
		default: goto yy34;
	}
yy109:
	yych = *++curr_;
	switch (yych) {
		case 'e': goto yy130;
		case 'i': goto yy132;
		default: goto yy34;
	}
yy110:
	yych = *++curr_;
	switch (yych) {
		case 'o': goto yy133;
		default: goto yy34;
	}
yy111:
	yych = *++curr_;
	switch (yych) {
		case 's': goto yy134;
		default: goto yy34;
	}
yy112:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy33;
		default: goto yy113;
	}
yy113:
#line 97 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_LET(loc_);
    }
#line 1341 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy114:
	yych = *++curr_;
	switch (yych) {
		case 'e': goto yy135;
		default: goto yy34;
	}
yy115:
	yych = *++curr_;
	switch (yych) {
		case 'a': goto yy137;
		default: goto yy34;
	}
yy116:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy33;
		default: goto yy117;
	}
yy117:
#line 109 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_NOT(loc_);
    }
#line 1427 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy118:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy33;
		default: goto yy119;
	}
yy119:
#line 113 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_OUT(loc_);
    }
#line 1501 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy120:
	yych = *++curr_;
	switch (yych) {
		case 's': goto yy138;
		default: goto yy34;
	}
yy121:
	yych = *++curr_;
	switch (yych) {
		case 'e': goto yy140;
		default: goto yy34;
	}
yy122:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy123;
		default: goto yy59;
	}
yy123:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy123;
		default: goto yy65;
	}
yy124:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy124;
		default: goto yy125;
	}
yy125:
#line 37 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_FLOAT(std::string_view{first, curr_}, loc_);
    }
#line 1565 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy126:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy33;
		default: goto yy127;
	}
yy127:
#line 65 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_BOOL(loc_);
    }
#line 1639 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy128:
	yych = *++curr_;
	switch (yych) {
		case 'e': goto yy142;
		default: goto yy34;
	}
yy129:
	yych = *++curr_;
	switch (yych) {
		case 'n': goto yy143;
		default: goto yy34;
	}
yy130:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy33;
		default: goto yy131;
	}
yy131:
#line 77 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_ELSE(loc_);
    }
#line 1725 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy132:
	yych = *++curr_;
	switch (yych) {
		case 'f': goto yy144;
		default: goto yy34;
	}
yy133:
	yych = *++curr_;
	switch (yych) {
		case 'r': goto yy146;
		default: goto yy34;
	}
yy134:
	yych = *++curr_;
	switch (yych) {
		case 'e': goto yy147;
		default: goto yy34;
	}
yy135:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy33;
		default: goto yy136;
	}
yy136:
#line 101 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_MOVE(loc_);
    }
#line 1817 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy137:
	yych = *++curr_;
	switch (yych) {
		case 'b': goto yy149;
		default: goto yy34;
	}
yy138:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy33;
		default: goto yy139;
	}
yy139:
#line 121 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_THIS(loc_);
    }
#line 1897 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy140:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy33;
		default: goto yy141;
	}
yy141:
#line 125 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_TRUE(loc_);
    }
#line 1971 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy142:
	yych = *++curr_;
	switch (yych) {
		case 'v': goto yy150;
		default: goto yy34;
	}
yy143:
	yych = *++curr_;
	switch (yych) {
		case 'e': goto yy151;
		default: goto yy34;
	}
yy144:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy33;
		default: goto yy145;
	}
yy145:
#line 81 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_ELSIF(loc_);
    }
#line 2057 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy146:
	yych = *++curr_;
	switch (yych) {
		case 't': goto yy153;
		default: goto yy34;
	}
yy147:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy33;
		default: goto yy148;
	}
yy148:
#line 89 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_FALSE(loc_);
    }
#line 2137 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy149:
	yych = *++curr_;
	switch (yych) {
		case 'l': goto yy155;
		default: goto yy34;
	}
yy150:
	yych = *++curr_;
	switch (yych) {
		case 'a': goto yy156;
		default: goto yy34;
	}
yy151:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy33;
		default: goto yy152;
	}
yy152:
#line 73 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_DEFINE(loc_);
    }
#line 2223 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy153:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy33;
		default: goto yy154;
	}
yy154:
#line 85 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_EXPORT(loc_);
    }
#line 2297 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy155:
	yych = *++curr_;
	switch (yych) {
		case 'e': goto yy157;
		default: goto yy34;
	}
yy156:
	yych = *++curr_;
	switch (yych) {
		case 'l': goto yy159;
		default: goto yy34;
	}
yy157:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy33;
		default: goto yy158;
	}
yy158:
#line 105 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_MUTABLE(loc_);
    }
#line 2383 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
yy159:
	yych = *++curr_;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy33;
		default: goto yy160;
	}
yy160:
#line 69 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"
	{
      loc_.columns(curr_ - first);
      return parser::make_COMPEVAL(loc_);
    }
#line 2457 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer.cpp"
}
#line 293 "/home/aschiffer/Fermi-Redux/src/syntax_analysis/lexer-in.cpp"

}

void fermi::lexer::skip_to_token() {
  while (curr_ != source_.cend() && std::isspace(*curr_)) {
    loc_.step();
    if (*curr_ == '\n') {
      loc_.lines(1);
    }
    ++curr_;
  }

  if (curr_ == source_.cend()) {
    return;
  }

  if (*curr_ == '#') {
    while (curr_ != source_.cend() && *curr_ != '\n') {
      loc_.step();
      ++curr_;
    }
    if (curr_ != source_.cend()) {
      loc_.step();
      loc_.lines(1);
      ++curr_;
    }
    skip_to_token();
  }
}

std::ostream& fermi::operator<<(std::ostream& os,
                                const parser::symbol_type& symbol) {
  os << "{Type: " << symbol.name() << ", value: ";
  const auto& value = symbol.value;
  const auto token_type = symbol.kind();

  if (token_type == parser::symbol_kind_type::S_CHARACTER ||
      token_type == parser::symbol_kind_type::S_COMPLEX ||
      token_type == parser::symbol_kind_type::S_FLOAT ||
      token_type == parser::symbol_kind_type::S_IDENTIFIER ||
      token_type == parser::symbol_kind_type::S_INTEGER ||
      token_type == parser::symbol_kind_type::S_STRING ||
      token_type == parser::symbol_kind_type::S_TYPE_NAME) {
    os << value.as<std::string_view>() << ", ";
  } else {
    os << symbol.name() << ", ";
  }
  os << "Start Column: " << symbol.location.begin.column << ", ";
  os << "End Column: " << symbol.location.end.column << ", ";
  os << "Line: " << symbol.location.begin.line << "}";
  return os;
}